<?php

return [
    'list_count' => 20,
    'hr_feature_slug' => [
        // 'cashbook',
        // 'asset',
        // 'asset.create',
        // 'fixed-asset',
        // 'fixed-asset.create',
        // 'account-payable.payment',

        // 'pos.home',
        // 'customer',
        // 'customer.create',
        // 'customer-deposit',
        // 'customer-deposit.confirm',
        // 'invoice.list', 
        // 'pos-cashbook',

        // 'inventory-stock',
        // 'inventory-transfer-history',
        // 'inventory-transfer-receive',
        // 'inventory-transfer',
        // 'inventory-transfer-confirm',

        // 'defect-item',

        // 'room-discount',
        // 'room-discount.create',
        // 'menu-service-discount',
        // 'package',
        // 'package.create',
        // 'accessory',
        // 'accessory.create',

        // 'staff',
        // 'staff.create',
        // 'staff.edit',
        // 'staff.toggle',
        // 'role',
        // 'role.create',
        // 'role.edit',
        // 'uom-conversion',
        // 'uom-conversion.create',
        // 'department',
        // 'department.create',
        // 'department.edit',
        // 'complain',
        // 'staff.complaints',
        // 'complain.create',
        // 'complaint.detail',
        // 'complaint.update',
        // 'complain.delete',
        // 'complain.toggle',
        // 'complaint.responsibles-by-staff',
        // 'complaint.carbon-copies-by-staff',
        // 'complaint.delete.image',
        // 'complaint.delete.responsible',
        // 'complaint.delete.carbon-copies',
        // 'complaint-category',
        // 'accessories.index',
        // 'accessories.store',
        // 'accessories.show',
        // 'accessory-category',
        // 'accessory-category.detail',
        // 'accessory-item.delete',
        // 'accessory.add',
        // 'duty.create',
        // 'duty',
        // 'duty.update',
        // 'duty.delete',
        // 'duty.edit',
        // 'menu-category',
        // 'menu-category.create',
        // 'menu-category.update',
        // 'menu-category.delete',
        // 'menu-category.toggle',
        // 'menu',
        // 'menu.create',
        // 'menu.edit',
        // 'menu.toggle',
        // 'menu-area',
        // 'menu-costing',
        // 'menu-sale-report',
        // 'sale-target-menu.list',
        // 'sale-target-position.list',
        // 'skill.list',
        // 'skill.create',
        // 'skill.edit',
        // 'skill.delete',
        // 'cooking-place',
        // 'cooking-place.create',
        // 'cooking-place.edit',
        // 'cooking-place.delete',
        // 'area.list',
        // 'area.create',
        // 'area.edit',
        // 'area.toggle',
        // 'brand',
        // 'brand.create',
        // 'brand.edit',
        // 'item',
        // 'item.detail',
        // 'item.create',
        // 'item-supplier.detail',
        // 'item-price.update',
        // 'item-type.import',
        // 'item-category.import',
        // 'item.import',
        // 'room',
        // 'room.create',
        // 'room.toggle',
        // 'table',
        // 'table.create',
        // 'table.toggle',
        // 'cash-flow',
        // 'indirect-cash-flow',
        // 'working-capital',
        // 'ap-balance',
        // 'creditor-balance',
        // 'journal.create',
        // 'journal',
        // 'staff-balance',
        // 'staff-balance.create',
        // 'prepaid.create',
        // 'prepaid-payment.create',
        // 'prepaid',
        // 'ar.create',
        // 'ar.list',
        // 'ar-payment.create',
        // 'task.create',
        // 'task.toggle',
        // 'custom-task.create',
        // 'custom-task',
        // 'custom-task.update',
        // 'report-task.create',
        // 'service.create',
        // 'service.toggle',
        // 'service.update',
        // 'inventory',
        // 'inventory.create',
        // 'inventory.update',
        // 'inventory.toggle',
        // 'supplier.create',
        // 'supplier',
        // 'supplier.edit',
        // 'supplier.delete',
        // 'account.create',
        // 'account',
        // 'account.edit',
        // 'account.delete',
        // 'financial-transaction',
        // 'financial-transaction.edit',
        // 'financial-transaction.delete',
        // 'financial-transaction.isconfirm',
        // 'financial-transaction.confirm_selected',
        // 'purchase-order.create',
        // 'purchase-order',
        // 'purchase-order.edit',
        // 'confirm-purchase-order-item.list',
        // 'asset-item',
        // 'asset-item.create',
        // 'account-payable',
        // 'okr.create',
        // 'okr',
        // 'okr.edit',
        // 'okr.delete',
        // 'okr-duties',
        // 'okr-duties.create',
        // 'okr-duties.edit',
        // 'okr-duties.delete',
        // 'okr-dashboard',
        // 'okr-duty',
        // 'okr-duty.create',
        // 'okr-duty.edit',
        // 'okr-duty.delete',
        // 'ktv-product-tree.create',
        // 'ktv-product-tree',
        // 'ktv-product-tree.edit',
        // 'ktv-product-tree.delete',
        // 'menu-forecasting',
        // 'menu-forecasting.create',
        // 'menu-forecasting.edit',
        // 'menu-forecasting.delete',
        // 'ktv-forecasting',
        // 'ktv-forecasting.create',
        // 'ktv-forecasting.edit',
        // 'ktv-forecasting.delete',
        // 'time-shift',
        // 'time-shift.create',
        // 'time-shift.edit',
        // 'time-shift.delete',
        // 'gps',
        // 'gps.edit',
        // 'check-in',
        // 'contact',
        // 'contact.create',
        // 'contact.edit',
        // 'contact.delete',
        // 'meeting.create',
        // 'meeting',
        // 'meeting.edit',
        // 'meeting.delete',
        // 'training',
        // 'training.create',
        // 'training.edit',
        // 'training.delete',
        // 'org-new',
        // 'org-new.create',
        // 'org-new.edit',
        // 'org-new.delete',
        // 'warning',
        // 'warning.create',
        // 'warning.edit',
        // 'warning.delete',
        // 'off-day',
        // 'off-day.create',
        // 'off-day.edit',
        // 'off-day.delete',
        // 'leave-allowance',
        // 'leave-allowance.create',
        // 'leave-allowance.edit',
        // 'leave-allowance.delete',
        // 'leave',
        // 'leave.delete',
        // 'exit-pass',
        // 'exit-pass.delete',
        // 'overtime-fee',
        // 'overtime-fee.create',
        // 'overtime-fee.edit',
        // 'overtime-fee.delete',
        // 'overtime-confirmation',
        // 'overtime-confirmation.create',
        // 'salary-setup',
        // 'salary-setup.create',
        // 'salary-setup.edit',
        // 'salary-setup.delete',
        // 'salary',
        // 'salary.create',
        // 'salary.edit',
        // 'salary.delete',
        // 'allowance',
        // 'allowance.create',
        // 'allowance.edit',
        // 'allowance.delete',
        // 'salary-batch',
        // 'salary-batch.create',
        // 'salary-batch.edit',
        // 'salary-batch.delete',
        // 'salary-calculate',
        // 'salary-calculate.create',
        // 'salary-calculate.publish',
        // 'pay-slip',
        // 'pay-slip.edit',
        // 'resignation-categories',
        // 'resignation-categories.create',
        // 'resignation',
        // 'resignation.create',
        // 'resignation.status',
        "staff",
        "staff.create",
        "staff.edit",
        "staff.toggle",
        "role",
        "role.create",
        "role.edit",
        "uom-conversion",
        "uom-conversion.create",
        "department",
        "department.create",
        "department.edit",
        "complaint",
        "staff.complaints",
        "complain.create",
        "complaint.detail",
        "complaint.update",
        "complain.delete",
        "complain.toggle",
        "complaint.responsibles-by-staff",
        "complaint.carbon-copies-by-staff",
        "complaint.delete.image",
        "complaint.delete.responsible",
        "complaint.delete.carbon-copies",
        "complaint-category",
        "accessory",
        "accessory.store",
        "accessory.show",
        "accessory-category",
        "accessory-category.detail",
        "accessory-item.delete",
        "accessory.add",
        "duty.create",
        "duty",
        "duty.update",
        "duty.delete",
        "duty.edit",
        "menu-category",
        "menu-category.create",
        "menu-category.update",
        "menu-category.delete",
        "menu-category.toggle",
        "menu",
        "menu.create",
        "menu.edit",
        "menu.toggle",
        "menu-area",
        "menu-costing",
        "menu-sale-report",
        "sale-target-menu",
        "sale-target-position",
        "skill",
        "skill.create",
        "skill.edit",
        "skill.delete",
        "cooking-place",
        "cooking-place.create",
        "cooking-place.edit",
        "cooking-place.delete",
        "area.list",
        "area.create",
        "area.edit",
        "area.toggle",
        "brand",
        "brand.create",
        "brand.edit",
        "item",
        "item.detail",
        "item.create",
        "item-supplier.detail",
        "item-price.update",
        "item-type.import",
        "item-category.import",
        "item.import",
        "room",
        "room.create",
        "room.toggle", 
        "table",
        "table.create",
        "table.toggle",
        "cash-flow",
        "indirect-cash-flow",
        "ap-balance",
        "creditor-balance",
        "journal.create",
        "journal",
        "staff-balance",
        "staff-balance.create",
        "prepaid.create",
        "prepaid-payment.create",
        "prepaid",
        "ar.create",
        "ar",
        "ar-payment.create",
        "task.create",
        "task.create",
        "task.toggle",
        "custom-task.create",
        "custom-task",
        "custom-task.update",
        "report-task",
        "service",
        "service.create",
        "service.toggle",
        "service.update",
        "inventory",
        "inventory.create",
        "inventory.update",
        "inventory.toggle",
        "supplier.create",
        "supplier",
        "supplier.edit",
        "supplier.delete",
        "account.create",
        "account",
        "account.edit",
        "account.toggle",
        "financial-transaction",
        "financial-transaction.create",
        "financial-transaction.edit",
        "financial-transaction.delete",
        "financial-transaction.isconfirm",
        "financial-transaction.confirm_selected",
        "cashbook",
        "purchase-order.create",
        "purchase-order",
        "purchase-order.edit",
        "purchase-order.confirm",
        "po-order",
        "po-order.confirm",
        "arrival-item",
        "arrival-item.confirm",
        "po-order-invoice",
        "po-order-invoice.paid",
        "asset-item",
        "asset-item.create",
        "asset",
        "asset.create",
        "fix-asset",
        "fix-asset.create",
        "asset-depreciation-balance",
        "account-payable",
        "okr.create",
        "okr",
        "okr.edit",
        "okr.delete",
        "okr-duty",
        "okr-duty.create",
        "okr-duty.edit",
        "okr-duty.delete",
        "okr-dashboard",
        "ktv-product-tree.create",
        "ktv-product-tree",
        "ktv-product-tree.edit",
        "ktv-product-tree.delete",
        "menu-forecasting",
        "menu-forecasting.create",
        "menu-forecasting.edit",
        "menu-forecasting.delete",
        "ktv-forecasting",
        "ktv-forecasting.create",
        "ktv-forecasting.edit",
        "ktv-forecasting.delete",
        "time-shift",
        "time-shift.create",
        "time-shift.edit",
        "time-shift.delete",
        "gps",
        "gps.edit",
        "check-in",
        "contact",
        "contact.create",
        "contact.edit",
        "contact.delete",
        "meeting.create",
        "meeting",
        "meeting.edit",
        "meeting.delete",
        "training",
        "training.create",
        "training.edit",
        "training.delete",
        "org-new",
        "org-new.create",
        "org-new.edit",
        "org-new.delete",
        "warning",
        "warning.create",
        "warning.edit",
        "warning.delete",
        "off-day",
        "off-day.create",
        "off-day.edit",
        "off-day.delete",
        "leave-allowance",
        "leave-allowance.create",
        "leave-allowance.edit",
        "leave-allowance.delete",
        "leave",
        "leave.create",
        "leave.delete",
        "exit-pass",
        "exit-pass.delete",
        "overtime-fee",
        "overtime-fee.create",
        "overtime-fee.edit",
        "overtime-fee.delete",
        "overtime-confirmation",
        "overtime-confirmation.create",
        "salary-setup",
        "salary-setup.create",
        "salary-setup.edit",
        "salary-setup.delete",
        "salary",
        "salary.create",
        "salary.edit",
        "salary.delete",
        "allowance",
        "allowance.create",
        "allowance.edit",
        "allowance.delete",
        "salary-batch",
        "salary-batch.create",
        "salary-batch.edit",
        "salary-batch.delete",
        "salary-calculate",
        "salary-calculate.create",
        "salary-calculate.publish",
        "pay-slip",
        "pay-slip.edit",
        "resignation-categories",
        "resignation-categories.create",
        "resignation",
        "resignation.create",
        "resignation.status",
        "customer",
        "customer-level-discount",
        "customer-level-discount.create",
        "customer-level-discount.edit",
        "customer-level-discount.delete",
        "customer-birthday",
        "customer-birthday-promotion",
        "inventory",
        "inventory-stock",
        "inventory-transfer",
        "inventory-receive",
        "used-defected-item",
        "room-discount",
        "room-discount.create",
        "room-discount.delete",
        "menu-service-discount",
        "menu-service-discount.create",
        "menu-service-discount.delete",
        "pos-home",
        "pos-customer",
        "pos-customer.create",
        "pos-customer-deposit",
        "pos-customer-deposit.confirm",
        "pos-invoice",
        "pos-cashbook",
        "pos-booking",
        "pos-food-order",
        "pos-ar",
        "event",
        "event.create",
        "package",
        "package.create",
        "pos-menu-sale-report",
        "jd",
        "jd.create",
        "js",
        "js.create",
        "sop",
        "sop.create",
        "sop.delete",
        "cv",
        "cv-salary.create",
        "cv.edit",
        "cv.delete"
    ],
    'finance_feature_slug' => [
        'staff',
        'staff.create',
        'staff.edit',
        'staff.toggle',
        'role',
        'role.create',
        'role.edit',
        'uom-conversion',
        'uom-conversion.create',
        'department',
        'department.create',
        'department.edit',
        'purchase-order.create',
        'purchase-order',
        'purchase-order.edit',
        'cashbook',
        'cash-flow',
        'indirect-cash-flow',
        'working-capital',
        'trial-balance',
        'profit-and-loss',
        'ap-balance',
        'creditor-balance',
        'journal.create',
        'journal',
        'staff-balance',
        'staff-balance.create',
        'prepaid.create',
        'prepaid-payment.create',
        'prepaid',
        'ar',
        'ar.create',
        'ar.list',
        'ar-payment.create',
        'ap-balance',
        'account.create',
        'account',
        'asset-item',
        'asset-item.create',
        "asset",
        "asset.create",
        "fix-asset",
        "fix-asset.create",
        "asset-depreciation-balance",
        'account-payableaccount.edit', // This looks like a typo, possibly should be two items?
        'account.delete',
        'financial-transaction',
        'financial-transaction.edit',
        'financial-transaction.delete',
        'financial-transaction.isconfirm',
        'financial-transaction.confirm_selected',
    ],
    'inventory_feature_slug' => [
        'inventory',
        'inventory.create',
        'inventory.update',
        'inventory.toggle',
        'inventory-stock',
        'inventory-transfer-history',
        'inventory-transfer-receive',
        'inventory-transfer',
        'inventory-transfer-confirm',
    ],
    'management_feature_slug' => [
        'staff',
        'staff.create',
        'staff.edit',
        'staff.toggle',
        'department',
        'department.create',
        'department.edit',
        'purchase-order.create',
        'purchase-order',
        'purchase-order.edit',
    ],
    'catering_feature_slug' => [
        'pos-home',
        'pos-customer',
        'pos-customer.create',
        // 'customer',
        // 'customer.create',
        'customer-deposit',
        'customer-deposit.confirm',
        'pos-invoice',
        'pos-cashbook',
        'pos-menu-sale-report',
        'pos-ar',
    ],
    'procurement_feature_slug' => [
        'staff',
        'staff.create',
        'staff.edit',
        'staff.toggle',
        'department',
        'department.create',
        'department.edit',
        'purchase-order.create',
        'purchase-order',
        'purchase-order.edit',
        'po-order',
        'po-order.confirm',
        'arrival-item',
        'arrival-item.confirm',
        'po-order-invoice',
        'po-order-invoice.paid',
    ],
    'pos_cash' => 33,
    'pos_bank' => 34,
    'liabilities' => 4,
    'payable_account_code' => '4-4000',
    'cash_code' => "2-1000",
    'creditor_account_code' => '4-2000',
    'cash_account_code'=>['2-1001','2-1002','2-1003','2-1004','2-1005','2-1006','2-1007','2-1008','2-1009','2-1010'],
    'pos_cash_account_code'=>['2-1011','2-1012'],
    'loan_account_code'=>'4-1001', //subheading - Liabilities
    'interest_on_loan_account_code'=>'6-8001', //subheading - Finance Cost

    // 'cash_account_code' => ['2-1001', '2-1002', '2-1003', '2-1004', '2-1005', '2-1006', '2-1007', '2-1008', '2-1009', '2-1010'],
    // 'pos_cash_account_code' => ['2-1011', '2-1012'],
    'expense_account_codes'=>[
        // 6-2xxx series
        '6-2001', '6-2002', '6-2003', '6-2004', '6-2005', '6-2006', '6-2007', '6-2008', '6-2009',
        // 6-3xxx series
        '6-3001', '6-3002', '6-3003', '6-3004', '6-3005', '6-3006', '6-3007', '6-3008', '6-3009', 
        '6-3010', '6-3011', '6-3012', '6-3013', '6-3014', '6-3015', '6-3016', '6-3017', '6-3018',
        // 6-4xxx series
        '6-4001', '6-4002', '6-4003', '6-4004', '6-4005', '6-4006', '6-4007',
        // 6-5xxx series
        '6-5001', '6-5002', '6-5003', '6-5004', '6-5005', '6-5006', '6-5007', '6-5008', '6-5009',
        '6-5010', '6-5011', '6-5012', '6-5013', '6-5014', '6-5015',
        // 6-6xxx series
        '6-6001', '6-6002', '6-6003', '6-6004', '6-6005', '6-6006',
        // 6-7xxx series
        '6-7001', '6-7002', '6-7003', '6-7004',
        // 6-8xxx series
        '6-8001', '6-8002',
        // 6-9xxx series
        '6-9001', '6-9002'
    ],

    'other_payable_account_codes'=> [
        '4-4003', '4-4004', '4-4005', '4-4006', '4-4007', '4-4008', '4-4009', '4-4010',
        '4-4011', '4-4012', '4-4013', '4-4014', '4-4015', '4-4016', '4-4017', '4-4018',
        '4-4019', '4-4020', '4-4021', '4-4022', '4-4023', '4-4024', '4-4025', '4-4026',
        '4-4027', '4-4028', '4-4029', '4-4030', '4-4031', '4-4032', '4-4033', '4-4034', '4-4035'
    ],
];
