<?php

return [
    'list_count' => 20,
    'hr_features' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    'finance_features' => [1, 15, 21, 22, 23, 31],
    // 'inventory_features' => [16, 17, 18, 19, 20, 21, 32],
    'hr_feature_slug' => [
        'staff',
        'role',
        'task',
        'complaint',
        'department',
        'area',
        'room',
        'room-discount',
        'table',
        'service',
        'brand',
        'item',
        'uom-conversion',
        'uom',
        'purchase-order',
        'purchase-order-confirmation',
        'crm',
        'sale-target',
        'duty',
        'asset-depreciation-balance',
        'journal',
        'staff-balance',
        'account-payables',
        'prepaid',
        'ar',
        'skill',
        'cooking-place',
        'feature',
        'accessory',
        'financial-report',
        'mrp',
        'objective',
        'ktv-product-tree',
        'package',
        'menu-service-discount',
        'item usage forecast',
        'purchase-order-confirmation',
        'inventory',
        'inventory-stocks',
        'inventory-confirmation',
        'inventory-transfer-list',
        'inventory-receive-list',
        'supplier',
        'cashbook',
        'fixed-asset',
        'customer',
        'hr',
        'check-in',
    ],
    'finance_feature_slug' => [
        'staff',
        'department',
        'purchase-order',
        'purchase-order-confirmation',
        'crm',
        'sale-target',
        'duty',
        'asset-depreciation-balance',
        'journal',
        'staff-balance',
        'prepaid',
        'ar',
        'account-payables',
        'skill',
        'cooking-place',
        'financial-report',
        'purchase-order-confirmation',
        'supplier',
        'cashbook',
        'fixed-asset',
    ],
    // 'inventory_feature_slug' => [
    //     'inventory',
    //     'inventory-stocks',
    //     'inventory-confirmation',
    //     'inventory-transfer-list',
    //     'inventory-receive-list',
    // ],
    'management_feature_slug' => [
        'staff',
        'purchase-order',
        'purchase-order-confirmation',
    ],
    'entertainment_feature_slug' => [
        'service',
        'staff',
    ],

    'catering_feature_slug' => [
        'pos',
        'inventory-stocks',
    ],
    'procurement_feature_slug'=>[
        'staff',
        'supplier',
        'item',
        'uom',
        'brand',
        'purchase-order',
        'po-order',
        'arrival-item',
        'po-order-invoice',
        'inventory',
        'inventory-stocks',
        'inventory-confirmation',
        'inventory-transfer-list',
        'inventory-receive-list',
    ],
    'management_features' => [1, 15, 32],
    'catering_features' => [27, 32],
    'pos_cash' => 33,
    'pos_bank' => 34,
    'liabilities' => 4,
    'payable_account_code' => '4-4000',
    'cash_code' => "2-1000",
    'creditor_account_code'=>'4-2000',
];
