<?php

return [
    'list_count' => 20,
    'hr_features' => [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 28, 29, 30, 32, 34, 35, 36, 37, 38, 39, 40, 41, 42],
    'finance_features' => [1, 15, 21, 22, 23, 31],
    // 'inventory_features' => [16, 17, 18, 19, 20, 21, 32],
    // 'hr_feature_slug' => [
    //     'staff',
    //     'role',
    //     'task',
    //     'complaint',
    //     'department',
    //     'area',
    //     'room',
    //     'room-discount',
    //     'table',
    //     'service',
    //     'brand',
    //     'item',
    //     'uom-conversion',
    //     'uom',
    //     'purchase-order',
    //     'purchase-order-confirmation',
    //     'crm',
    //     'sale-target',
    //     'duty',
    //     'asset-depreciation-balance',
    //     'journal',
    //     'staff-balance',
    //     'account-payables',
    //     'prepaid',
    //     'ar',
    //     'skill',
    //     'cooking-place',
    //     'feature',
    //     'accessory',
    //     'financial-report',
    //     'mrp',
    //     'objective',
    //     'ktv-product-tree',
    //     'package',
    //     'menu-service-discount',
    //     'item usage forecast',
    //     'purchase-order-confirmation',
    //     'inventory',
    //     'inventory-stocks',
    //     'inventory-confirmation',
    //     'inventory-transfer-list',
    //     'inventory-receive-list',
    //     'supplier',
    //     'cashbook',
    //     'fixed-asset',
    //     'customer',
    //     'hr',
    //     'check-in',
    // ],
    'hr_feature_slug' => [
        'cashbook',
        'asset',
        'asset.create',
        'fixed-asset',
        'fixed-asset.create',
        'account-payable.payment',

        'pos.home',
        'customer',
        'customer.create',
        'customer-deposit',
        'customer-deposit.confirm',
        'invoice.list',
        'pos-cashbook',

        'inventory-stock',
        'inventory-transfer-history',
        'inventory-transfer-receive',
        'inventory-transfer',
        'inventory-transfer-confirm',

        'defect-item',

        'room-discount',
        'room-discount.create',
        'menu-service-discount',
        'package',
        'package.create',
        'accessory',
        'accessory.create',

        'staff',
        'staff.create',
        'staff.edit',
        'staff.toggle',
        'role',
        'role.create',
        'role.edit',
        'uom-conversion',
        'uom-conversion.create',
        'department',
        'department.create',
        'department.edit',
        'complain',
        'staff.complaints',
        'complain.create',
        'complaint.detail',
        'complaint.update',
        'complain.delete',
        'complain.toggle',
        'complaint.responsibles-by-staff',
        'complaint.carbon-copies-by-staff',
        'complaint.delete.image',
        'complaint.delete.responsible',
        'complaint.delete.carbon-copies',
        'complaint-category',
        'accessories.index',
        'accessories.store',
        'accessories.show',
        'accessory-category',
        'accessory-category.detail',
        'accessory-item.delete',
        'accessory.add',
        'duty.create',
        'duty',
        'duty.update',
        'duty.delete',
        'duty.edit',
        'menu-category',
        'menu-category.create',
        'menu-category.update',
        'menu-category.delete',
        'menu-category.toggle',
        'menu',
        'menu.create',
        'menu.edit',
        'menu.toggle',
        'menu-area',
        'menu-costing',
        'menu-sale-report',
        'sale-target-menu.list',
        'sale-target-position.list',
        'skill.list',
        'skill.create',
        'skill.edit',
        'skill.delete',
        'cooking-place',
        'cooking-place.create',
        'cooking-place.edit',
        'cooking-place.delete',
        'area.list',
        'area.create',
        'area.edit',
        'area.toggle',
        'brand',
        'brand.create',
        'brand.edit',
        'item',
        'item.detail',
        'item.create',
        'item-supplier.detail',
        'item-price.update',
        'item-type.import',
        'item-category.import',
        'item.import',
        'room',
        'room.create',
        'room.toggle',
        'table',
        'table.create',
        'table.toggle',
        'cash-flow',
        'indirect-cash-flow',
        'working-capital',
        'ap-balance',
        'creditor-balance',
        'journal.create',
        'journal',
        'staff-balance',
        'staff-balance.create',
        'prepaid.create',
        'prepaid-payment.create',
        'prepaid',
        'ar.create',
        'ar.list',
        'ar-payment.create',
        'task.create',
        'task.toggle',
        'custom-task.create',
        'custom-task',
        'custom-task.update',
        'report-task.create',
        'service.create',
        'service.toggle',
        'service.update',
        'inventory',
        'inventory.create',
        'inventory.update',
        'inventory.toggle',
        'supplier.create',
        'supplier',
        'supplier.edit',
        'supplier.delete',
        'account.create',
        'account',
        'account.edit',
        'account.delete',
        'financial-transaction',
        'financial-transaction.edit',
        'financial-transaction.delete',
        'financial-transaction.isconfirm',
        'financial-transaction.confirm_selected',
        'purchase-order.create',
        'purchase-order',
        'purchase-order.edit',
        'purchase-order.confirm',
        'confirm-purchase-order-item.list',
        'asset-item',
        'asset-item.create',
        'account-payable',
        'okr.create',
        'okr',
        'okr.edit',
        'okr.delete',
        'okr-duties',
        'okr-duties.create',
        'okr-duties.edit',
        'okr-duties.delete',
        'okr-dashboard',
        'ktv-product-tree.create',
        'ktv-product-tree',
        'ktv-product-tree.edit',
        'ktv-product-tree.delete',
        'menu-forecasting',
        'menu-forecasting.create',
        'menu-forecasting.edit',
        'menu-forecasting.delete',
        'ktv-forecasting',
        'ktv-forecasting.create',
        'ktv-forecasting.edit',
        'ktv-forecasting.delete',
        'time-shift',
        'time-shift.create',
        'time-shift.edit',
        'time-shift.delete',
        'gps',
        'gps.edit',
        'check-in.list',
        'contact',
        'contact.create',
        'contact.edit',
        'contact.delete',
        'meeting.create',
        'meeting',
        'meeting.edit',
        'meeting.delete',
        'training',
        'training.create',
        'training.edit',
        'training.delete',
        'org-new',
        'org-new.create',
        'org-new.edit',
        'org-new.delete',
        'warning',
        'warning.create',
        'warning.edit',
        'warning.delete',
        'off-day',
        'off-day.create',
        'off-day.edit',
        'off-day.delete',
        'leave-allowance',
        'leave-allowance.create',
        'leave-allowance.edit',
        'leave-allowance.delete',
        'leave',
        'leave.delete',
        'exit-pass',
        'exit-pass.delete',
        'overtime-fee',
        'overtime-fee.create',
        'overtime-fee.edit',
        'overtime-fee.delete',
        'overtime-confirmation',
        'overtime-confirmation.create',
        'salary-setup',
        'salary-setup.create',
        'salary-setup.edit',
        'salary-setup.delete',
        'salary',
        'salary.create',
        'salary.edit',
        'salary.delete',
        'allowance',
        'allowance.create',
        'allowance.edit',
        'allowance.delete',
        'salary-batch',
        'salary-batch.create',
        'salary-batch.edit',
        'salary-batch.delete',
        'salary-calculate',
        'salary-calculate.create',
        'salary-calculate.publish',
        'pay-slip',
        'pay-slip.edit',
        'resignation-categories',
        'resignation-categories.create',
        'resignation',
        'resignation.create',
        'resignation.status',
    ],
    'finance_feature_slug' => [
        'cash-flow',
        'indirect-cash-flow',
        'working-capital',
        'ap-balance',
        'creditor-balance',
        'journal.create',
        'journal',
        'staff-balance',
        'staff-balance.create',
        'prepaid.create',
        'prepaid-payment.create',
        'prepaid',
        'ar.create',
        'ar.list',
        'ar-payment.create',
        'account.create',
        'account',
        'asset-item',
        'asset-item.create',
        'account-payableaccount.edit', // This looks like a typo, possibly should be two items?
        'account.delete',
        'financial-transaction',
        'financial-transaction.edit',
        'financial-transaction.delete',
        'financial-transaction.isconfirm',
        'financial-transaction.confirm_selected',
    ],
    // 'finance_feature_slug' => [
    //     'staff',
    //     'department',
    //     'purchase-order',
    //     'purchase-order-confirmation',
    //     'crm',
    //     'sale-target',
    //     'duty',
    //     'asset-depreciation-balance',
    //     'journal',
    //     'staff-balance',
    //     'prepaid',
    //     'ar',
    //     'account-payables',
    //     'skill',
    //     'cooking-place',
    //     'financial-report',
    //     'purchase-order-confirmation',
    //     'supplier',
    //     'cashbook',
    //     'fixed-asset',
    // ],
    // 'inventory_feature_slug' => [
    //     'inventory',
    //     'inventory-stocks',
    //     'inventory-confirmation',
    //     'inventory-transfer-list',
    //     'inventory-receive-list',
    // ],
    // 'management_feature_slug' => [
    //     'staff',
    //     'purchase-order',
    //     'purchase-order-confirmation',
    // ],
    'management_feature_slug' => [
        'staff',
        'purchase_order',
    ],
    // 'entertainment_feature_slug' => [
    //     'service',
    //     'staff',
    // ],
    // 'catering_feature_slug' => [
    //     'pos',
    //     'inventory-stocks',
    // ],
    'procurement_feature_slug' => [
        'staff',
        'supplier',
        'item',
        'uom',
        'brand',
        'purchase-order',
        'po-order',
        'arrival-item',
        'po-order-invoice',
        'inventory',
        'inventory-stock',
        'inventory-transfer-history',
        'inventory-transfer-receive',
        'inventory-transfer',
        'inventory-transfer-confirm',
    ],
    'management_features' => [1, 15, 32],
    'catering_features' => [27, 32],
    'pos_cash' => 33,
    'pos_bank' => 34,
    'liabilities' => 4,
    'payable_account_code' => '4-4000',
    'cash_code' => "2-1000",
    'creditor_account_code' => '4-2000',
];
