<?php

return [
   
    'staff' => 'staff',
    'role' => 'roles',
    'task' => 'tasks',
    'complaint' => 'complains',
    'department' => 'departments',
    'area' => 'areas',
    'room' => 'room',
    'table' => 'table',
    'service' => 'services',
    'item' => 'items',
    'brand' => 'brands',
    'uom-conversion' => 'uom_conversions',
    'uom' => 'uoms',
    'menu' => 'MRP.index',
    'item-usage-forecast' => 'item_usage_forecasts',
    'purchase-order' => 'purchase_orders',
    'purchase-order-confirmation' => 'purchase_orders.confirm_poitems',
    'inventory' => 'inventories',
    'inventory-stock' => 'inventory_stocks.index',
    'inventory-transfer' => 'transfers.transfers',
    'inventory-receive' => 'transfers.receives',
    'supplier' => 'suppliers.index',
    'customer' => 'pos.customers',
    'purchase-order-item-left' => 'purchase_orders.left_items_index',
    'purchase-order-item-left-confirmation' => 'purchase_orders.left_items_detail',
    'pos' => 'pos.index',
    'room-discount' => 'room_discount.index',
    'package' => 'packages.index',
    'menu-service-discount' => 'menu_service_discount.index',
    'account-payable' => 'AP.index',

    //financial
    'fixed-asset' => 'fixed_assets.index',
    'cash-flow-statement' => 'cash_flow_statement.index',
    'sale-target-menu' => 'sale_target_position.index',
    'duty' => 'duty.index',
    'asset-depreciation-balance' => 'asset_depreciation_balance.index',
    'journal' => 'journals.index',
    'staff-balance' => 'advanced.index',
    'prepaid' => 'prepaid.index',
    'ar' => 'AR.index',
    'cashbook'=>'cashbook',
    'pos_cashbook'=>'pos.cashbooks',
    //financial

    'skill' => 'skill.index',
    'cooking-place' => 'cookingPlace.index',
    'custom-task' => 'tasks.customtask',
    'accessory' => 'accessories.index',
    'okr' => 'OKR.index',
    'ktv-product-tree' => 'product_tree.index',
    //procurement
    'po-order'=>'procurement_order_items.index',   //procurement order-item
    'arrival-item'=>'procurement_order_arrival.index',
    'po-invoice'=>'purchase_order_invoices.index',   //purchase order invoice listc
    'check-in'=>'check_in.index', 
    //end procurement

    //added
    'menu-category' => 'menu_categories.index',
    'sale-target-position'=> 'sale_target_position.index',
    'account'=> 'accounting.index',// chart of account (COA)
    'financial-transaction'=> 'financial_transaction.index',
    'asset-item'=> 'fixed_assets.asset_item_list',
    'okr-duty'=> 'okr_duty.index',
    'okr-dashboard'=> 'okr_dashboard.index',
    'menu-forecasting'=> 'menu_forecastings.index',
    'ktv-forecasting'=> 'ktv_forecastings.index',
    'time-shift'=> 'time_shift.index',
    'gps'=> 'GPS.index',
    'contact'=> 'contact.index',
    'meeting'=> 'meeting.index',
    'training'=>'training.index',
    'org-new'=>'org_news.index',
    'warning'=>'warning.index',
    'off-day'=>'off_day.index',
    'leave-allowance'=>'leave_allowance.index',
    'leave'=>'leave.index',
    'exit-pass'=>'exit_pass.index',
    'overtime-fee'=>'overtime_fees.index',
    'salary-setup'=>'salary_setup.index',
    'salary'=>'salary.index',
    'allowance'=>'allowance.index',
    'salary-batch'=>'salary_batch.index',
    'pay-slip'=>'salary_calculate.pay_slip',
    'resignation'=>'resignations.index',
    'resignation-categories'=>'resignation_categories.index',
    'customer-level-discount'=>'CRM.level_discounts.index',
    'customer-birthday'=>'CRM.customers.birthdays',
    'birthday-promotion'=>'CRM.birthday_discounts.index',
    'used-defected-item'=>'used_defected_items.index',

];
