<?php

return [
   
    'staff' => 'staff',
    'role' => 'roles',
    'task' => 'tasks',
    'complaint' => 'complains',
    'department' => 'departments',
    'area' => 'areas',
    'room' => 'room',
    'table' => 'table',
    'service' => 'services',
    'item' => 'items',
    'brand' => 'brands',
    'uom-conversion' => 'uom_conversions',
    'uom' => 'uoms',
    'menu' => 'MRP.index',
    'item-usage-forecast' => 'item_usage_forecasts',
    'purchase-order' => 'purchase_orders',
    'purchase-order-confirmation' => 'purchase_orders.confirm_poitems',
    'inventory' => 'inventories',
    'inventory-stock' => 'inventory_stocks.index',
    'inventory-transfer' => 'transfers.transfers',
    'inventory-receive' => 'transfers.receives',
    'supplier' => 'suppliers.index',
    'customer' => 'pos.customers',
    'purchase-order-item-left' => 'purchase_orders.left_items_index',
    'purchase-order-item-left-confirmation' => 'purchase_orders.left_items_detail',
    'pos' => 'pos.index',
    'room-discount' => 'room_discount.index',
    'package' => 'packages.index',
    'menu-service-discount' => 'menu_service_discount.index',
    'account-payable' => 'AP.index',

    //financial
    'fixed-asset' => 'fixed_assets.index',
    'cash-flow-statement' => 'cash_flow_statement.index',
    'sale-target-menu' => 'sale_target_position.index',
    'duty' => 'duty.index',
    'asset-depreciation-balance' => 'asset_depreciation_balance.index',
    'journal' => 'journals.index',
    'staff-balance' => 'advanced.index',
    'prepaid' => 'prepaid.index',
    'ar' => 'AR.index',
    'cashbook'=>'pos.cashbook.index',
    //financial

    'skill' => 'skill.index',
    'cooking-place' => 'cookingPlace.index',
    'custom-task' => 'tasks.customtask',
    'accessory' => 'accessories.index',
    'okr' => 'OKR.index',
    'ktv-product-tree' => 'product_tree.index',
    //procurement
    'po-order'=>'procurement_order_items.index',   //procurement order-item
    'arrival-item'=>'procurement_order_arrival.index',
    'po-invoice'=>'purchase_order_invoices.index',   //purchase order invoice listc
    'hr'=>'meeting.index',   //
    'check-in'=>'check_in.index', 
    //end procurement

    //added
    'menu-category' => '',
    'sale-target-position'=>'',
    'account'=> '',// chart of account (COA)
    'financial-transaction'=>'',
    'asset-item'=>'',
    'okr-duty'=>'',
    'okr-dashboard'=>'',
    'menu-forecasting'=>'',
    'ktv-forecasting'=>'',
    'time-shift'=>'',
    'gps'=>'',
    'contact'=>'',
    'meeting'=>'',
    'training'=>'',
    'org-new'=>'',
    'warning'=>'',
    'off-day'=>'',
    'leave-allowance'=>'',
    'leave'=>'',
    'exit-pass'=>'',
    'overtime-fee'=>'',
    'salary-setup'=>'',
    'salary'=>'',
    'allowance'=>'',
    'salary-batch'=>'',
    'pay-slip'=>'',
    'resignation'=>'',
    'resignation-categories'=>'',
    'customer-level-discount'=>'',
    'customer-birthday'=>'',
    'birthday-promotion'=>'',
    'used-defected-item'=>'',

];
