<?php

return [
    // 'staff' => 'staff',
    // 'role' => 'roles',
    // 'task' => 'tasks',
    // 'complaint' => 'complains',
    // 'department' => 'departments',
    // 'area' => 'areas',
    // 'room' => 'room',
    // 'table' => 'table',
    // 'service' => 'services',
    // //'item'=>'tes',
    // 'uom-conversion' => 'uom_conversions',
    // 'uom' => 'uoms',
    // 'menu' => 'menus',
    // 'item-usage-forecast' => 'item_usage_forecasts',
    // 'purchase-order' => 'purchase_orders',
    // 'purchase-order-confirmation' => 'purchase_orders.confirm', #not sure
    // 'inventory' => 'inventories',
    // 'inventory-confirmation' => 'transfers.index',
    // 'inventory-transfer-list' => 'transfers.transfers',
    // 'inventory-receive-list' => 'transfers.receives',
    // 'supplier' => 'suppliers.index',
    // 'cashbook' => 'cashbook',
    // 'fixed-asset' => 'fixed_assets.index',
    // 'customer' => 'pos.customers',
    // 'purchase-order-item-left' => 'purchase_orders.left_items_index', //not sure
    // 'purchase-order-item-left-confirmation' => 'purchase_orders.left_items_index', //not sure
    // 'pos' => 'pos.index',
    // 'room-discount' => 'room_discount.index',
    // 'package' => 'packages.index',
    // 'menu-service-discount' => 'menu_service_discount.index',
    // 'account-payables' => 'AP.index',
    // 'inventory-stocks' => 'inventory_stocks.index',

    'staff' => 'staff',
    'role' => 'roles',
    'task' => 'tasks',
    'complaint' => 'complains',
    'department' => 'departments',
    'area' => 'areas',
    'room' => 'room',
    'table' => 'table',
    'service' => 'services',
    'item' => 'items',
    'brand' => 'brands',
    'uom-conversion' => 'uom_conversions',
    'uom' => 'uoms',
    'menu' => 'menus',
    'item-usage-forecast' => 'item_usage_forecasts',
    'purchase-order' => 'purchase_orders',
    'purchase-order-confirmation' => 'purchase_orders.confirm_poitems',
    'inventory' => 'inventories',
    'inventory-transfer-list' => 'transfers.transfers',
    'inventory-receive-list' => 'transfers.receives',
    'supplier' => 'suppliers.index',
    'cashbook' => 'cashbook',
    'customer' => 'pos.customers',
    'purchase-order-item-left' => 'purchase_orders.left_items_index',
    'purchase-order-item-left-confirmation' => 'purchase_orders.left_items_detail',
    'pos' => 'pos.index',
    'room-discount' => 'room_discount.index',
    'package' => 'packages.index',
    'menu-service-discount' => 'menu_service_discount.index',
    'account-payables' => 'AP.index',
    'inventory-stocks' => 'inventory_stocks.index',

    //financial
    'fixed-asset' => 'fixed_assets.index',
    'cash-flow-statement' => 'cash_flow_statement.index',
    'sale-target' => 'sale_target_position.index',
    'duty' => 'duty.index',
    'asset-depreciation-balance' => 'asset_depreciation_balance.index',
    'journal' => 'journals.index',
    'staff-balance' => 'advanced.index',
    'prepaid' => 'prepaid.index',
    'ar' => 'AR.index',
    //financial

    'skill' => 'skill.index',
    'cooking-place' => 'cookingPlace.index',
    'custom-task' => 'tasks.customtask',
    'feature' => 'accessories.index',
    'MRP' => 'MRP.index',
    'Objective' => 'OKR.index',
    'ktv-product-tree' => 'product_tree.index',
    //procurement
    'po-order'=>'procurement_order_items.index',   //procurement order-item
    'arrival-item'=>'procurement_order_arrival.index',
    'po-invoice'=>'purchase_order_invoices.index',   //purchase order invoice listc
    'hr'=>'meeting.index',   //
    'check-in'=>'check_in.index', 

    //end procurement
];
