<?php
return [
    'modules' => [
        "staff",
        "staff",
        "staff",
        "staff",
        "role",
        "role",
        "role",
        "uom-conversion",
        "uom-conversion",
        "department",
        "department",
        "department",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complain",
        "complaint-category",
        "accessory",
        "accessory",
        "accessory",
        "accessory",
        "accessory",
        "accessory",
        "accessory",
        "duty",
        "duty",
        "duty",
        "duty",
        "duty",
        "menu-category",
        "menu-category",
        "menu-category",
        "menu-category",
        "menu-category",
        "menu",
        "menu",
        "menu",
        "menu",
        "menu-area",
        "menu-costing",
        "menu-sale-report",
        "sale-target-menu",
        "sale-target-position",
        "skill",
        "skill",
        "skill",
        "skill",
        "cooking-place",
        "cooking-place",
        "cooking-place",
        "cooking-place",
        "area",
        "area",
        "area",
        "area",
        "brand",
        "brand",
        "brand",
        "item",
        "item",
        "item",
        "item",
        "item",
        "item",
        "item",
        "item",
        "room",
        "room",
        "room",
        "table",
        "table",
        "table",
        "cash-flow",
        "indirect-cash-flow",
        "ap-balance",
        "creditor-balance",
        "journal",
        "journal",
        "staff-balance",
        "staff-balance",
        "prepaid",
        "prepaid",
        "prepaid",
        "ar",
        "ar",
        "ar",
        "task",
        "task",
        "task",
        "custom-task",
        "custom-task",
        "custom-task",
        "report-task",
        "service",
        "service",
        "service",
        "service",
        "inventory",
        "inventory",
        "inventory",
        "inventory",
        "supplier",
        "supplier",
        "supplier",
        "supplier",
        "chartofaccount",
        "chartofaccount",
        "chartofaccount",
        "chartofaccount",
        "financial-transaction",
        "financial-transaction",
        "financial-transaction",
        "financial-transaction",
        "financial-transaction",
        "financial-transaction",
        "purchase-order",
        "purchase-order",
        "purchase-order",
        "purchase-order",
        "cashbook",
        "confirm-purchase-order-item",
        "po-order",
        "po-order",
        "arrival-item",
        "arrival-item",
        "po-order-invoice",
        "po-order-invoice",
        "asset-item",
        "asset-item",
        "account-payable",
        "okr",
        "okr",
        "okr",
        "okr",
        "okr-duty",
        "okr-duty",
        "okr-duty",
        "okr-duty",
        "okr-dashboard",
        "ktv-product-tree",
        "ktv-product-tree",
        "ktv-product-tree",
        "ktv-product-tree",
        "menu-forecasting",
        "menu-forecasting",
        "menu-forecasting",
        "menu-forecasting",
        "ktv-forecasting",
        "ktv-forecasting",
        "ktv-forecasting",
        "ktv-forecasting",
        "time-shift",
        "time-shift",
        "time-shift",
        "time-shift",
        "gps",
        "gps",
        "check-in",
        "contact",
        "contact",
        "contact",
        "contact",
        "meeting",
        "meeting",
        "meeting",
        "meeting",
        "training",
        "training",
        "training",
        "training",
        "org-new",
        "org-new",
        "org-new",
        "org-new",
        "warning",
        "warning",
        "warning",
        "warning",
        "off day",
        "off day",
        "off day",
        "off day",
        "leave-allowance",
        "leave-allowance",
        "leave-allowance",
        "leave-allowance",
        "leave",
        "leave",
        "leave",
        "exit-pass",
        "exit-pass",
        "overtime-fee",
        "overtime-fee",
        "overtime-fee",
        "overtime-fee",
        "overtime-confirmation",
        "overtime-confirmation",
        "salary-setup",
        "salary-setup",
        "salary-setup",
        "salary-setup",
        "salary",
        "salary",
        "salary",
        "salary",
        "allowance",
        "allowance",
        "allowance",
        "allowance",
        "salary-batch",
        "salary-batch",
        "salary-batch",
        "salary-batch",
        "salary-calculate",
        "salary-calculate",
        "salary-calculate",
        "pay-slip",
        "pay-slip",
        "resignation-categories",
        "resignation-categories",
        "resignation",
        "resignation",
        "resignation",
        "customer",
        "customer-level-discount",
        "customer-level-discount",
        "customer-level-discount",
        "customer-level-discount",
        "customer-birthday",
        "customer-birthday-promotion",
        "inventory",
        "inventory-stock",
        "inventory-transfer",
        "inventory-receive",
        "used-defected-item",
        "room-discount",
        "room-discount",
        "room-discount",
        "menu-service-discount",
        "menu-service-discount",
        "menu-service-discount",
        "pos-home",
        "pos-customer",
        "pos-customer-deposit",
        "pos-customer-deposit",
        "pos-invoice",
        "pos-cashbook",
        "pos-booking",
        "pos-food-order",
        "pos-ar",
        "event",
        "event",
        "package",
        "package"
    ],
    'names' => [
        "Staff List",
        "Staff Create",
        "Staff Edit",
        "Staff Active On/Off",
        "Role List",
        "Role Create",
        "Role Edit",
        "Uom Conversion LIst",
        "Uom Conversion Create",
        "Department List",
        "Department Create",
        "Department Edit",
        "getComplainData",
        "getStaffComplaints",
        "createComplain",
        "complaintDetail",
        "updateComplain",
        "deleteComplain",
        "complainStatusChange",
        "complaintResponsiblesByStaff",
        "complaintCarbonCopiesByStaff",
        "deleteComplaintImage",
        "deleteComplaintResponsible",
        "deleteComplaintCarbonCopy",
        "ComplaintCategory",
        "accessories list",
        "accessories create",
        "accessories show",
        "getAccessoryCategory",
        "getAccessoryByCategory",
        "deleteAccessoryItem",
        "createInvoiceAccessory",
        "createDuty",
        "listDuties",
        "updateDuty",
        "deleteDuty",
        "dutyDetail",
        "Menu Category List",
        "Menu Category Create",
        "Menu Category Update",
        "Menu Category Delete",
        "Menu Category Active On/Off",
        "Menu List",
        "Menu Create",
        "Menu Edit",
        "Menu Active On/Off",
        "Menu Area List",
        "Menu Costing List",
        "Menu Sale Report List",
        "Sale Target Menu List",
        "Sale Target Position List",
        "Skill List",
        "Skill Create",
        "Skill Edit",
        "Skill Delete",
        " Cooking Place List",
        "Cooking Place Create",
        "Cooking Place Edit ",
        "Cooking Place Delete",
        "Area List",
        "Area Create",
        "Area Edit",
        "Area Active On/Off",
        "Brand list",
        "Brand Create",
        "Brand Edit",
        "Item List",
        "Item Detail",
        "Item Create",
        "Item Supplier Detail",
        "Item Price Update",
        "Item Type Import",
        "Item Category Import",
        "Item Import",
        "Room List",
        "Room Create",
        "Room Active On/Off",
        "Table List",
        "Table Create",
        "Table Active On/Off",
        "Cash Flow List",
        "Indirect Cash Flow List",
        "Ap Balance",
        "creditor-balance",
        "journal create",
        "journal list",
        "Staff Balance List",
        "staff balance create",
        "prepaid create",
        "Prepaid Payment",
        "prepaid list",
        "AR create",
        "AR list",
        "AR Payment",
        "Task Create",
        "Task List",
        "Task Status",
        "custom task create",
        "custom task list",
        "custom taskupdate",
        "report task list",
        "service list",
        "service create ",
        "service Active On/Off",
        "service update",
        "inventory list",
        "inventory create",
        "inventory update",
        "inventory active on/off",
        "supplier create",
        "supplier list",
        "supplier edit",
        "supplier delete",
        "account create",
        "account list",
        "account edit",
        "account active on/off",
        "financial-transaction list",
        "financial transaction create",
        "financial-transaction edit",
        "financial-transaction delete ",
        "financial-transaction isconfirm",
        "financial-transaction confirm selected",
        "cashbook list",
        "purchase-order create",
        "purchase-order list",
        "purchase-order edit",
        "purchase-order confirm",
        "confirm-purchase-order-item  list",
        "Po Order List",
        "Po Order Confirm",
        "Arrival Item List",
        "Arrival Item Confirm",
        "Po Order Invoice List",
        "Po Order Invoice Paid",
        "asset-item list ",
        "asset-item create",
        "account-payable list",
        "OKR create",
        "OKR list",
        "OKR edit",
        "OKR delete",
        "OKR duty list",
        "OKR duty create",
        "OKR duty edit",
        "OKR duty delete",
        "okr-dashboard list ",
        "ktv-product-tree create",
        "ktv-product-tree list",
        "ktv-product-tree edit",
        "ktv-product-tree delete",
        "menu-forecasting list",
        "menu-forecasting create",
        "menu-forecasting edit",
        "menu-forecasting delete",
        "ktv-forecasting  list",
        "ktv-forecasting create",
        "ktv-forecasting edit",
        "ktv-forecasting delete",
        "time-shift list",
        "time-shift create",
        "time-shift edit",
        "time-shift delete",
        "gps list",
        "gps edit",
        "check-in list",
        "contact",
        "contact create",
        "contact edit",
        "contact delete",
        "meeting create",
        "meeting list ",
        "meeting edit",
        "meeting delete",
        "training list",
        "training create",
        "training edit",
        "training delete",
        "org-new list",
        "org-new create",
        "org-new edit",
        "org-new delete",
        "warning list",
        "warning create",
        "warning edit ",
        "warning delete",
        "off day list",
        "off-day create",
        "off-day edit",
        "off-day delete",
        "leave-allowance list",
        "leave-allowance create",
        "leave-allowance edit ",
        "leave-allowance delete",
        "leave list",
        "leave create",
        "leave delete ",
        "exit-pass list",
        "exit-pass delete",
        "overtime-fee list",
        "overtime-fee create",
        "overtime-fee edit",
        "overtime-fee delete",
        "overtime-confirmation list",
        "overtime-confirmation create",
        "salary-setup list",
        "salary-setup create",
        "salary-setup edit",
        "salary-setup delete",
        "salary list",
        "salary create",
        "salary edit",
        "salary delete",
        "allowance list",
        "allowance create",
        "allowance edit",
        "allowance delete",
        "salary-batch list",
        "salary-batch create",
        "salary-batch edit",
        "salary-batch delete",
        "salary-calculate list",
        "salary-calculate create",
        "salary-calculate publish",
        "pay-slip list",
        "pay-slip edit",
        "resignation-categories list",
        "resignation-categories create ",
        "resignation list",
        "resignation create",
        "resignation status",
        "customer list ",
        "customer level  discount list",
        "customer level  discount create",
        "customer level  discount edit",
        "customer level  discount  delete ",
        "customer birthday list",
        "customer-birthday-promotion list",
        "inventory list",
        "Inventory Stock List",
        "inventory-transfer list",
        "inventory-receive list",
        "used-defected-item list ",
        "room-discount list ",
        "room-discount create",
        "room-discount delete",
        "menu-service-discount list ",
        "menu-service-discount create",
        "menu-service-discount delete",
        "pos-home",
        "pos customer list",
        "pos-customer-deposit",
        "Pos Customer Deposit Confirm",
        "invoice list",
        "pos-cashbook list ",
        "pos booking list ",
        "pos-food-order list",
        "pos-ar list",
        "event list",
        "event create",
        "package list",
        "package create",
    ],
    'slug' => [
        "staff",
        "staff.create",
        "staff.edit",
        "staff.toggle",
        "role",
        "role.create",
        "role.edit",
        "uom-conversion",
        "uom-conversion.create",
        "department",
        "department.create",
        "department.edit",
        "complaint",
        "staff.complaints",
        "complain.create",
        "complaint.detail",
        "complaint.update",
        "complain.delete",
        "complain.toggle",
        "complaint.responsibles-by-staff",
        "complaint.carbon-copies-by-staff",
        "complaint.delete.image",
        "complaint.delete.responsible",
        "complaint.delete.carbon-copies",
        "complaint-category",
        "accessory",
        "accessory.store",
        "accessory.show",
        "accessory-category",
        "accessory-category.detail",
        "accessory-item.delete",
        "accessory.add",
        "duty.create",
        "duty",
        "duty.update",
        "duty.delete",
        "duty.edit",
        "menu-category",
        "menu-category.create",
        "menu-category.update",
        "menu-category.delete",
        "menu-category.toggle",
        "menu",
        "menu.create",
        "menu.edit",
        "menu.toggle",
        "menu-area",
        "menu-costing",
        "menu-sale-report",
        "sale-target-menu",
        "sale-target-position",
        "skill",
        "skill.create",
        "skill.edit",
        "skill.delete",
        "cooking-place",
        "cooking-place.create",
        "cooking-place.edit",
        "cooking-place.delete",
        "area.list",
        "area.create",
        "area.edit",
        "area.toggle",
        "brand",
        "brand.create",
        "brand.edit",
        "item",
        "item.detail",
        "item.create",
        "item-supplier.detail",
        "item-price.update",
        "item-type.import",
        "item-category.import",
        "item.import",
        "room",
        "room.create",
        "room.toggle",
        "table",
        "table.create",
        "table.toggle",
        "cash-flow",
        "indirect-cash-flow",
        "ap-balance",
        "creditor-balance",
        "journal.create",
        "journal",
        "staff-balance",
        "staff-balance.create",
        "prepaid.create",
        "prepaid-payment.create",
        "prepaid",
        "ar.create",
        "ar",
        "ar-payment.create",
        "task.create",
        "task.create",
        "task.toggle",
        "custom-task.create",
        "custom-task",
        "custom-task.update",
        "report-task",
        "service",
        "service.create",
        "service.toggle",
        "service.update",
        "inventory",
        "inventory.create",
        "inventory.update",
        "inventory.toggle",
        "supplier.create",
        "supplier",
        "supplier.edit",
        "supplier.delete",
        "account.create",
        "account",
        "account.edit",
        "account.toggle",
        "financial-transaction",
        "financial-transaction.create",
        "financial-transaction.edit",
        "financial-transaction.delete",
        "financial-transaction.isconfirm",
        "financial-transaction.confirm_selected",
        "cashbook",
        "purchase-order.create",
        "purchase-order",
        "purchase-order.edit",
        "purchase-order.confirm",
        "confirm-purchase-order-item.list",
        "po-order",
        "po-order.confirm",
        "arrival-item",
        "arrival-item.confirm",
        "po-order-invoice",
        "po-order-invoice.paid",
        "asset-item",
        "asset-item.create",
        "account-payable",
        "okr.create",
        "okr",
        "okr.edit",
        "okr.delete",
        "okr-duty",
        "okr-duty.create",
        "okr-duty.edit",
        "okr-duty.delete",
        "okr-dashboard",
        "ktv-product-tree.create",
        "ktv-product-tree",
        "ktv-product-tree.edit",
        "ktv-product-tree.delete",
        "menu-forecasting",
        "menu-forecasting.create",
        "menu-forecasting.edit",
        "menu-forecasting.delete",
        "ktv-forecasting",
        "ktv-forecasting.create",
        "ktv-forecasting.edit",
        "ktv-forecasting.delete",
        "time-shift",
        "time-shift.create",
        "time-shift.edit",
        "time-shift.delete",
        "gps",
        "gps.edit",
        "check-in",
        "contact",
        "contact.create",
        "contact.edit",
        "contact.delete",
        "meeting.create",
        "meeting",
        "meeting.edit",
        "meeting.delete",
        "training",
        "training.create",
        "training.edit",
        "training.delete",
        "org-new",
        "org-new.create",
        "org-new.edit",
        "org-new.delete",
        "warning",
        "warning.create",
        "warning.edit",
        "warning.delete",
        "off-day",
        "off-day.create",
        "off-day.edit",
        "off-day.delete",
        "leave-allowance",
        "leave-allowance.create",
        "leave-allowance.edit",
        "leave-allowance.delete",
        "leave",
        "leave.create",
        "leave.delete",
        "exit-pass",
        "exit-pass.delete",
        "overtime-fee",
        "overtime-fee.create",
        "overtime-fee.edit",
        "overtime-fee.delete",
        "overtime-confirmation",
        "overtime-confirmation.create",
        "salary-setup",
        "salary-setup.create",
        "salary-setup.edit",
        "salary-setup.delete",
        "salary",
        "salary.create",
        "salary.edit",
        "salary.delete",
        "allowance",
        "allowance.create",
        "allowance.edit",
        "allowance.delete",
        "salary-batch",
        "salary-batch.create",
        "salary-batch.edit",
        "salary-batch.delete",
        "salary-calculate",
        "salary-calculate.create",
        "salary-calculate.publish",
        "pay-slip",
        "pay-slip.edit",
        "resignation-categories",
        "resignation-categories.create",
        "resignation",
        "resignation.create",
        "resignation.status",
        "customer",
        "customer-level-discount",
        "customer-level-discount.create",
        "customer-level-discount.edit",
        "customer-level-discount.delete",
        "customer-birthday",
        "customer-birthday-promotion",
        "inventory",
        "inventory-stock",
        "inventory-transfer",
        "inventory-receive",
        "used-defected-item",
        "room-discount",
        "room-discount.create",
        "room-discount.delete",
        "menu-service-discount",
        "menu-service-discount.create",
        "menu-service-discount.delete",
        "pos-home",
        "pos-customer",
        "pos-customer-deposit",
        "pos-customer-deposit.confirm",
        "pos-invoice",
        "pos-cashbook",
        "pos-booking",
        "pos-food-order",
        "pos-ar",
        "event",
        "event.create",
        "package",
        "package.create",
    ],
];